name: Run Serenity Tests with Chrome

on:
  workflow_dispatch:
    inputs:
      gradle_command:
        description: 'Comando Gradle (ej: ./gradlew test -Dcucumber.filter.tags="@ttest")'
        required: true
        default: './gradlew test'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Chrome (latest stable)
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          echo "Chrome version: $(google-chrome --version)"

      - name: Run Serenity Tests
        run: ${{ github.event.inputs.gradle_command }}

      - name: Generate Serenity Report
        if: always()
        run: ./gradlew aggregate

      - name: Upload Serenity Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: serenity-report
          path: target/site/serenity
